Update grab_fw_Mint.yml

diff --git a/.github/workflows/grab_fw_Mint.yml b/.github/workflows/grab_fw_Mint.yml
--- a/.github/workflows/grab_fw_Mint.yml
+++ b/.github/workflows/grab_fw_Mint.yml
@@ -42,6 +42,12 @@ jobs:
         with:
           retain: 'compiler_cmake'
 
+      - name: Ignore erroring out
+        run: |
+          source ./buildenv.sh m51
+          find "$SRC_DIR/unica" "$SRC_DIR/scripts" -type f -name "*.sh" -exec sed -i "s/exit 1/LOGE \"failed\"/g" {} +
+          find "$SRC_DIR/scripts" -type f -name "*.sh" -exec sed -i "s/return 1/return 0/g" {} +
+          
       - name: Set up build environment
         run: |
           sudo apt update
@@ -54,13 +60,7 @@ jobs:
           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
           echo -n "${{ secrets.PLATFORM_KEY_PK8 }}" | base64 --decode > security/unica_platform.pk8
           echo -n "${{ secrets.PLATFORM_KEY_PEM }}" | base64 --decode > security/unica_platform.x509.pem
-      
-      - name: Ignore erroring out
-        run: |
-          source ./buildenv.sh m51
-          find "$SRC_DIR/unica" "$SRC_DIR/scripts" -type f -name "*.sh" -exec sed -i "s/exit 1/LOGE \"failed\"/g" {} +
-          find "$SRC_DIR/scripts" -type f -name "*.sh" -exec sed -i "s/return 1/return 0/g" {} +
-          
+
       - name: Set up JDK 21
         uses: actions/setup-java@v5
         with:
